# Config file to run PoseidonMRV.jl

# Model choice
model: "CrankNicholson1D"

# Model setup
setup: "finite_ELD_newBiotNum_test"

# Oceanographic Properties
ocn_props:
  vertical_diffusivity_ML: 1.51e-6 # [m^2/s]
  temperature: 15.0 # [C]
  salinity: 35.0 # [psu]
  alk_sw: 2300.0 # [umol/kgSW]
  dic_sw: 2050.0 # [umol/kgSW]

# Atmospheric Properties
atm_props:
  pCO2_air: 344.19 # [umol/kgSW]
  u_10: 6.63 # [m/s]

# Vertical Grid
depth_grid:
  max_depth: 50.0
  dz: 0.250

# Timstepping (for CrankNicholson use)
# consider the CN stability criterion when setting timestep: 
# dt_max = dz^2 / (2 * max_vertical_diffusivity)
timestepping:
  timestep: 3600 # [s]
  sim_duration_days: 30.0
  save_interval_hours: 1

# Perturbation Properties
pert_props:
  dilution: 100  # dilution factor [1]
  alk_pert: 2300.0 # [umol/kgSW] use 2700 for perturbation, 2300 for baseline
  dic_pert: 1050.0 # [umol/kgSW] use 1050 for perturbation, 2050 for baseline
  perturbed_layer_thickness: 1.0  # general layer thickness [m]
  perturbation_depth_start: 1.0 # deep layer runs from pert_depth_start to (pert_depth_start + pert_layer_thickness)[m]
  perturbation_depth_center: 2.0 # for the Gaussian perturbation [m]
  perturbation_width: 1.0 # for the Gaussian perturbation [m]

# CO2SYS Parameters
co2sys_params:
  total_silicate: 5.0       # (umol/kgSW) from WOCE: https://www.nodc.noaa.gov/cgi-bin/OC5/WOA09F/woa09f.pl - show less than 10 mmol/m³ in most of the ocean
  total_phosphate: 0.5    # (umol/kgSW) from WOCE: https://www.nodc.noaa.gov/cgi-bin/OC5/WOA09F/woa09f.pl
  total_ammonia: 0.0        # (umol/kgSW) ammonium - https://www.researchgate.net/figure/Seasonal-mean-surface-seawater-concentration-of-total-ammonium-NHxsw-simulated-by_fig2_346365160
  total_sulfide: 0.0        # (umol/kgSW) usually small at the surface - https://www.researchgate.net/figure/Hydrogen-Sulphide-concentrations-in-the-Black-Sea_fig2_320416797
  opt_pH_scale: 1         # 1 = Total pH scale, 2 = Seawater scale
  opt_k_carbonic: 10      # Constants from Leuker et al (2000) K1K2
  opt_k_bisulfate: 1      # Constants from Dickson (1990) KSO4
  opt_k_fluoride: 2       # Constants from Perez & Fraga (1987) KF
  opt_total_borate: 2     # Lee et al (2010) TB

# # Atmospheric Data
# pH20: 0.0227
# pAir: 1
# xCO2atm: 535
